### ISSUE TITLE
This can be achieved with a CSS snippet!

### ISSUE THREAD

**Issue by witecat** [yszk0123/obsidian-floating-action-button#5]
A relatively simple snippet, see here:

https://forum.obsidian.md/t/adding-floating-action-button-fab-for-your-mobile-using-css/61388*/

**Comment by yszk0123** [comment]
@witecat 
Thank you for sharing the information!
I'm no longer actively maintaining this plugin, but I will make sure to add a deprecation comment in the README along with your link.

- https://github.com/yszk0123/obsidian-floating-action-button/pull/6
